version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    restart: always
    volumes:
      - "data:/data/db"
    env_file:
      - "./env/mongo.env"

  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    image: "backend"
    container_name: "backend-app"
    env_file:
      - "./env/backend.env"
    ports:
      - "80:80"
    volumes:
      - "logs:/app/logs"
      - "./backend:/app"
      - "/app/node_modules"
    depends_on:
      - "mongodb"

  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    image: "frontend"
    container_name: "frontend-app"
    depends_on:
      - "backend"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/app/src"
    stdin_open: true
    tty: true

volumes:
  data:
  logs:
