version: "3.8"
services:
  mongodb:
    image: "mongo"
    restart: always
    volumes:
      - "data:/data/db"
    env_file:
      - "./env/mongo.env"

  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    image: "backend"
    env_file:
      - "./env/backend.env"
    ports:
      - "80:80"
    volumes:
      - "logs:/app/logs"
      - "./backend:/app"
      - "/app/node_modules"
    depends_on:
      - "mongodb"

volumes:
  data:
  logs:
