apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: first-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers:
        - name: kube-node
          image: "thyashley/kube-node:2"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
